spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: investmentsPet
  datasource:
    url: ${INVEST_DB_URL}
    driverClassName: org.postgresql.Driver
    username: ${INVEST_DB_USER}
    password: ${INVEST_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
token:
  signing:
    key: ${INVEST_JWT_SECRET}

adminKey: ${INVEST_ADM_SECRET}
apiKey: ${INVEST_LLM_API_SECRET}
