
CREATE TABLE stock
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticker        VARCHAR(255)                            NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    sector        SMALLINT                                NOT NULL,
    last_price    DOUBLE PRECISION                        NOT NULL,
    available_for SMALLINT                                NOT NULL,
    logo          BYTEA,
    CONSTRAINT pk_stock PRIMARY KEY (id)
);

ALTER TABLE stock
    ADD CONSTRAINT uc_stock_name UNIQUE (name);

ALTER TABLE stock
    ADD CONSTRAINT uc_stock_ticker UNIQUE (ticker);
