CREATE TABLE brokerage_position
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id    BIGINT                                  NOT NULL,
    stock_id      BIGINT                                  NOT NULL,
    quantity      DECIMAL(19, 4)                          NOT NULL,
    average_price DECIMAL(19, 4)                          NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_brokerage_position PRIMARY KEY (id)
);

ALTER TABLE brokerage_position
    ADD CONSTRAINT uc_64af0c2f16ee1b7bf08562a12 UNIQUE (account_id, stock_id);

ALTER TABLE brokerage_position
    ADD CONSTRAINT FK_POSITION_ACCOUNT FOREIGN KEY (account_id) REFERENCES brokerage_account (user_id);

ALTER TABLE brokerage_position
    ADD CONSTRAINT FK_POSITION_STOCK FOREIGN KEY (stock_id) REFERENCES stock (id);