
CREATE TABLE stock_prices
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    price       DOUBLE PRECISION,
    last_update TIMESTAMP WITHOUT TIME ZONE,
    stock_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_stock_prices PRIMARY KEY (id)
);

ALTER TABLE stock_prices
    ADD CONSTRAINT FK_STOCK_PRICES_ON_STOCK FOREIGN KEY (stock_id) REFERENCES stock (id);