
CREATE TABLE stock
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticker           VARCHAR(255)                            NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    sector           VARCHAR(255)                            NOT NULL,
    available_for    VARCHAR(255)                            NOT NULL,
    logo             BYTEA,
    change_target_id BIGINT,
    CONSTRAINT pk_stock PRIMARY KEY (id)
);

ALTER TABLE stock
    ADD CONSTRAINT uc_stock_change_target UNIQUE (change_target_id);

ALTER TABLE stock
    ADD CONSTRAINT uc_stock_name UNIQUE (name);

ALTER TABLE stock
    ADD CONSTRAINT uc_stock_ticker UNIQUE (ticker);

ALTER TABLE stock
    ADD CONSTRAINT FK_STOCK_CHANGE_TARGET FOREIGN KEY (change_target_id) REFERENCES stock_change_target (id);