CREATE TABLE bugs
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    title   VARCHAR(255)                            NOT NULL,
    text    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_bugs PRIMARY KEY (id)
);

ALTER TABLE bugs
    ADD CONSTRAINT uc_bugs_user UNIQUE (user_id);

ALTER TABLE bugs
    ADD CONSTRAINT FK_BUGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

CREATE TABLE bugs
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    title   VARCHAR(255)                            NOT NULL,
    text    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_bugs PRIMARY KEY (id)
);