
CREATE TABLE brokerage_account
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    balance    DECIMAL(15, 2)                          NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_brokerageaccount PRIMARY KEY (id)
);

ALTER TABLE brokerage_account
    ADD CONSTRAINT uc_c2dbd19c235a8f3f10141b8c6 UNIQUE (user_id);

ALTER TABLE brokerage_account
    ADD CONSTRAINT FK_BROKERAGEACCOUNT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);