
CREATE TABLE stock_change_target
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    current_price  DOUBLE PRECISION                        NOT NULL,
    start_price    DOUBLE PRECISION                        NOT NULL,
    target_percent DOUBLE PRECISION,
    pattern        SMALLINT,
    grow_speed     SMALLINT,
    last_updated   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_stock_change_target PRIMARY KEY (id)
);